name: Development Branch Workflow

on:
  push:
    branches: [ "development" ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      jacoco_report: true
      build_frontend: true
    secrets: inherit
  
  deploy-to-dev:
    needs: [reusable-workflow]
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts