name: Feature Branch Workflow

on:
  pull_request:
    branches: [ "development" ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      jacoco_report: true
    secrets: inherit

  code-coverage:
    runs-on: ubuntu-latest
    needs: reusable-workflow

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build and verify coverage
      run: ./gradlew build jacocoTestCoverageVerification

    - name: Run tests with JaCoCo
      run: ./gradlew test jacocoTestReport

    - name: Check code coverage
      run: ./gradlew check