name: Feature Branch Workflow

on:
  pull_request:
    branches: [ "development" ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      jacoco_report: true
      build_frontend: true
    secrets: inherit

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with JaCoCo
      run: ./gradlew test jacocoTestReport

    - name: Check code coverage
      run: |
        COVERAGE=$(grep -oP 'instruction, \K[0-9]+(?=%)' build/reports/jacoco/test/jacocoTestReport.xml)
        if [ "$COVERAGE" -lt 70 ]; then
          echo "Code coverage is below 70%: $COVERAGE%"
          exit 1
        fi

  check-coverage:
    needs: reusable-workflow
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Run tests with JaCoCo
      run: ./gradlew test jacocoTestReport

    - name: Check code coverage
      run: |
        COVERAGE=$(grep -oP 'instruction, \K[0-9]+(?=%)' build/reports/jacoco/test/jacocoTestReport.xml)
        if [ "$COVERAGE" -lt 70 ]; then
          echo "Code coverage is below 70%: $COVERAGE%"
          exit 1 