name: Feature Branch Workflow

on:
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build and Test
        run: ./gradlew build test
      
      - name: SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -Dsonar.projectKey=mono-web-nbody-sim -Dsonar.organization=your-organization -Dsonar.host.url=https://sonarcloud.io
        
  build-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build Frontend
        run: yarn build
      
      - name: Test Frontend
        run: yarn test --if-present 