name: Reusable Workflow

on:
  workflow_call:
    inputs:
      jacoco_report:
        description: 'Generate JaCoCo report'
        required: false
        type: boolean
        default: true
      security_analysis:
        description: 'Run security analysis'
        required: false
        type: boolean
        default: false
      production_build:
        description: 'Build for production'
        required: false
        type: boolean
        default: false
      build_frontend:
        description: 'Build frontend'
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build and Test
        run: ./gradlew build test
      
      - name: Code Coverage with JaCoCo
        if: ${{ inputs.jacoco_report }}
        run: ./gradlew jacocoTestReport
      
      - name: Generate Badge for Test Coverage
        if: ${{ inputs.jacoco_report }}
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: "**/build/reports/jacoco/test/jacocoTestReport.csv"
          badges-directory: .github/badges
          
      - name: Upload Code Coverage
        if: ${{ inputs.jacoco_report }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            **/build/reports/jacoco/
            **/build/reports/tests/
            .github/badges/

  build-artifacts:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() && needs.build-and-test.result == 'success' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build JAR files
        run: |
          if [[ "${{ inputs.production_build }}" == "true" ]]; then
            ./gradlew assemble -Pprod
          else
            ./gradlew assemble
          fi
      
      - name: Build Frontend
        if: ${{ inputs.build_frontend }}
        working-directory: ./frontend
        run: |
          yarn install --frozen-lockfile
          yarn build
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/build/libs/*.jar
            frontend/dist/ 